### ISSUE TITLE
Use variables from helm env instead of hardcoded values

### ISSUE THREAD

**Issue by tommy-dk** [ChristofferNissen/helmper#5] opened 2024-05-08 13:41 UTC
Hello!

When using `helmper` on a Mac it uses `~/.cache/helm`, but it's configured to use `~/Library/helm`. I suggest to use the built-in values from `helm env` instead of assuming where the files are located.

**Comment by ChristofferNissen** [comment] 2024-05-10 12:34
Hello :wave: 

Great suggestions, will look into implementing shortly

**Comment by ChristofferNissen** [comment] 2024-05-10 15:44
This issue should have been fixed in the PR above. I will release v0.1.2 shortly, please confirm the issue is indeed closed :man_technologist:

**Closed by ChristofferNissen** 2024-05-10 15:44 UTC
